baseURL = "http://localhost:1313/"
languageCode = "nb-no"
title = "Accountia"
enableRobotsTXT = true

defaultContentLanguage = "no"
defaultContentLanguageInSubdir = false

[languages]

  [languages.no]
    languageName = "Norsk"
    weight = 1
    contentDir = "content"
    [languages.no.params]
      siteName = "Accountia"
      orgnr = "936 229 239"
      address = "Oterdalen 58, 5914 Isdalstø"
      phone = "483 42 461"
      email = "post.acountia@gmail.com"
      openhours = "Åpent 08:00–16:00 (man–fre)"

    [languages.no.menu]
      [[languages.no.menu.main]]
        name = "Forside"
        url = "/"
        weight = 1
      [[languages.no.menu.main]]
        name = "Tjenester"
        url = "/tjenester/"
        weight = 2
      [[languages.no.menu.main]]
        name = "Om oss"
        url = "/om-oss/"
        weight = 3
      [[languages.no.menu.main]]
        name = "Kontakt"
        url = "/kontakt/"
        weight = 4
      [[languages.no.menu.main]]
        name = "Personvern"
        url = "/personvern/"
        weight = 5
      [[languages.no.menu.main]]
        name = "Priser"
        url = "/priser/"
        weight = 6

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      siteName = "Accountia"
      orgnr = "936 229 239"
      address = "Oterdalen 58, 5914 Isdalstø"
      phone = "+47 483 42 461"
      email = "post.acountia@gmail.com"
      openhours = "Open 08:00–16:00 (Mon–Fri)"

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        url = "/en/"
        weight = 1
      [[languages.en.menu.main]]
        name = "Services"
        url = "/en/services/"
        weight = 2
      [[languages.en.menu.main]]
        name = "About"
        url = "/en/about/"
        weight = 3
      [[languages.en.menu.main]]
        name = "Contact"
        url = "/en/contact/"
        weight = 4
      [[languages.en.menu.main]]
        name = "Privacy"
        url = "/en/privacy/"
        weight = 5
      [[languages.en.menu.main]]
        name = "Pricing"
        url = "/en/prices/"
        weight = 6

disableKinds = ["taxonomy", "term"]
