baseURL = "http://localhost:1313/"
languageCode = "nb-no"
title = "Accountia"
enableRobotsTXT = true

[params]
  siteName = "Accountia"
  orgnr = "936 229 239"
  address = "Oterdalen 58, 5914 Isdalstø"
  phone = "483 42 461"
  email = "post.acountia@gmail.com"
  openhours = "Åpent 08:00–16:00 (man–fre)"

[menu]
  [[menu.main]]
    name = "Forside"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tjenester"
    url = "/tjenester/"
    weight = 2
  [[menu.main]]
    name = "Om oss"
    url = "/om-oss/"
    weight = 3
  [[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 4
  [[menu.main]]
    name = "Personvern"
    url = "/personvern/"
    weight = 5
disableKinds = ["taxonomy", "term"]

